cash_flow/urls.py
from django.urls import path
from . import views

app_name = 'cash_flow'

urlpatterns = [
    path('', views.cash_flow, name='cash_flow'),
    path('meses_filtro/', views.filter_months_cash_flow, name='filter_months_cash_flow'),
    path('deletar_entradas/', views.delete_entries, name='delete_entries'),
    path('exibir_bancos/', views.display_banks, name='display_banks'),
    path('processar_transferencia/', views.process_transfer, name='process_transfer'),
    path('processar_liquidacao/', views.process_settlement, name='process_settlement'),
    path('pegar_parcelas_relacionadas/<uuid:correlation_id>/', views.get_related_installments, name='get_related_installments'),
]

chart_of_accounts/urls.py
from django.urls import path
from . import views

app_name = 'chart_of_accounts'

urlpatterns = [
    path('', views.chart_of_accounts, name='chart_of_accounts'),
    path('adicionar-conta/', views.add_account, name='adicionar_conta'),
    path('get-groups/', views.get_groups, name='get_groups'),
    path('get-subgroups/', views.get_subgroups, name='get_subgroups'),
    path('editar-conta/<int:account_id>/', views.edit_account, name='edit_account'),
    path('delete-account/<int:account_id>/', views.delete_account, name='delete_account'),
]

configuracoes/urls.py
from django.urls import path, include
from . import views

app_name = 'configuracoes'

urlpatterns = [
    path('', views.settings, name='settings'),
    path('bancos_e_contas/', views.banks, name='banks'),
    path('departamentos/', views.departments, name='departments'),
    path('salvar_banco/', views.save_bank, name='save_bank'),
    path('salvar_departamento/', views.save_department, name='save_department'),
    path('verificar_e_excluir_banco/<int:idBanco>/', views.verify_and_delete_bank, name='verify_and_delete_bank'),
    path('verificar_e_excluir_departamento/<int:idDepartamento>/', views.verify_and_delete_department, name='verify_and_delete_department'),
]

realizado/urls.py
from django.urls import path
from . import views

app_name = 'realizado'

urlpatterns = [
    path('', views.settled_entry, name='settled_entry'),
    path('meses_filtro_realizado/', views.filter_months_settled, name='filter_months_settled'),
    path('processar_retorno/', views.process_return, name='process_return'),
    path('atualizar-lancamento/<int:id>/', views.update_entry, name='update_entry'),
    path('atualizar-lancamentos-uuid/<str:uuid_transference>/', views.update_entries_by_uuid, name='update_entries_by_uuid'),
]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('', views.reports, name='reports'),
    path('cash_flow_report/', views.cash_flow_report, name='cash_flow_report'),
]

settings/urls.py
from django.urls import path, include
from . import views

app_name = 'settings'

urlpatterns = [
    path('', views.settings, name='settings'),
    path('bancos_e_contas/', views.banks, name='banks'),
    path('departamentos/', views.departments, name='departments'),
    path('estoque/', views.inventory, name='inventory'),
    path('cadastro/', views.entities, name='entities'),
    path('salvar_banco/', views.save_bank, name='save_bank'),
    path('salvar_departamento/', views.save_department, name='save_department'),
    path('salvar_estoque/', views.save_inventory, name='save_inventory'),
    path('salvar_entidade/', views.save_entity, name='save_entity'),
    path('verificar_e_excluir_banco/<int:bank_id>/', views.verify_and_delete_bank, name='verify_and_delete_bank'),
    path('verificar_e_excluir_departamento/<int:department_id>/', views.verify_and_delete_department, name='verify_and_delete_department'),
    path('verificar_e_excluir_estoque/<int:inventory_item_id>/', views.verify_and_delete_inventory, name='verify_and_delete_inventory'),
    path('verificar_e_excluir_entidade/<int:entity_id>/', views.verify_and_delete_entity, name='verify_and_delete_entity'),
]

spifex/urls.py
from django.contrib import admin
from django.urls import path, include
from registration import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fluxo_de_caixa/', include(('cash_flow.urls', 'cash_flow'), namespace='cash_flow')),
    path('realizado/', include(('settled_entry.urls', 'settled_entry'), namespace='settled_entry')),
    path('configuracoes/', include(('settings.urls', 'settings'), namespace='settings')),
    path('accounts/', include('registration.urls')),
    path('home/', views.HomePage, name='home'),
    path('logout/', views.LogoutPage, name='logout'),
    path('configuracoes/plano_de_contas/', include(('chart_of_accounts.urls', 'chart_of_accounts'), namespace='chart_of_accounts')),
    path('relatorios/', include(('reports.urls', 'reports'), namespace='reports')),
    path('configuracoes/projetos/', include(('projects.urls', 'projects'), namespace='projects')),
]

settings/models.py
from django.db import models

settings/views.py
import uuid
from decimal import Decimal
from django.shortcuts import render
from django.http import JsonResponse
from cash_flow.models import Banks, Departments, Inventory, Entities
from settled_entry.models import SettledEntry
from django.db.models import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

def settings(request):
    if request.method =="GET":
        return render(request, 'settings.html')

def banks(request):
    if request.method =="GET":
        banks_list = Banks.objects.all().order_by('id')

        context = {
            'Banks_list': banks_list,
        }
        return render(request, 'banks_and_accounts.html', context)
    
def departments(request):
    if request.method =="GET":
        departments_list = Departments.objects.all().order_by('id')

        context = {
            'Departments_list': departments_list,
        }
        return render(request, 'departments.html', context)
    
def inventory(request):
    if request.method =="GET":
        inventory_list = Inventory.objects.all().order_by('id')

        context = {
            'Inventory_list': inventory_list,
        }
        return render(request, 'inventory.html', context)
    
def entities(request):
    if request.method =="GET":
        entities_list = Entities.objects.all().order_by('id')

        context = {
            'Entities_list': entities_list,
        }
        return render(request, 'entities.html', context)
    
@csrf_exempt
def save_bank(request):
    # Retorna erro se não for uma requisição POST
    if request.method != 'POST':
        return JsonResponse({"success": False, "error": "Método não permitido."}, status=405)
    
    initial_balance_str = request.POST.get('bank_initial_balance', 'R$ 0,00').replace('R$ ', '').replace('.', '').replace(',', '.')
    initial_balance = Decimal(initial_balance_str) if initial_balance_str else Decimal('0.00')

    bank_id = request.POST.get('bank_id')
    bank_name = request.POST.get('bank_name')
    bank_branch = request.POST.get('bank_branch')
    bank_account = request.POST.get('bank_account')
    bank_status = request.POST.get('bank_status') == 'ativo'

    try:
        if bank_id:  # Atualização
            banks_table = Banks.objects.get(pk=bank_id)
            was_updated = banks_table.bank != bank_name  # Verifica se a descrição do banco foi atualizada
        else:  # Criação
            banks_table = Banks()
            was_updated = False

        banks_table.bank = bank_name
        banks_table.bank_branch = bank_branch
        banks_table.bank_account = bank_account
        banks_table.initial_balance = initial_balance
        banks_table.bank_status = bank_status
        banks_table.save()

        # Se a descrição do banco foi atualizada, atualiza também em SettledEntry
        if was_updated:
            SettledEntry.objects.filter(settlement_bank_id=banks_table.id).update(settlement_bank=bank_name)

        # Resposta JSON para atualização dinâmica
        return JsonResponse({"success": True, "id": banks_table.id})
    except ObjectDoesNotExist:
        # Banco não encontrado para atualização
        return JsonResponse({"success": False, "error": "Banco não encontrado."}, status=404)

@require_POST
def verify_and_delete_bank(request, bank_id):
    # Verifica se o banco está sendo utilizado na SettledEntry
    if SettledEntry.objects.filter(settlement_bank_id=bank_id).exists():
        # Banco está sendo utilizado, não pode ser excluído
        return JsonResponse({'success': False, 'error': 'Este banco está sendo utilizado e não pode ser excluído.'})

    try:
        # Tenta encontrar e excluir o banco
        bank_to_detele = Banks.objects.get(pk=bank_id)
        bank_to_detele.delete()
        # Banco excluído com sucesso
        return JsonResponse({'success': True})
    except Banks.DoesNotExist:
        # Banco não encontrado
        return JsonResponse({'success': False, 'error': 'Banco não encontrado.'})
    
@require_POST
def save_department(request):
    department_id = request.POST.get('department_id')
    department_name = request.POST.get('department')

    if department_id:
        # Atualizar um department existente
        try:
            department_list = Departments.objects.get(pk=department_id)
            # Verifica se o nome é diferente para evitar conflito de nome único
            if department_list.department != department_name and Departments.objects.filter(department=department_name).exists():
                return JsonResponse({'success': False, 'message': 'Por favor, escolha um nome diferente para o departmento.'})
            department_list.department = department_name
            department_list.save()
            return JsonResponse({'success': True, 'message': 'Departamento atualizado com sucesso.'})
        except Departments.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Departamento não encontrado.'})
    else:
        # Criar um novo department
        if Departments.objects.filter(department=department_name).exists():
            return JsonResponse({'success': False, 'message': 'Por favor, escolha um nome diferente para o departmento.'})
        
        new_department = Departments(
            department=department_name,
            uuid_department=uuid.uuid4()
        )
        new_department.save()

        return JsonResponse({'success': True, 'message': 'Departamento adicionado com sucesso.'})

@require_POST
def verify_and_delete_department(request, department_id):
    try:
        # Tenta encontrar e excluir o department
        department_list = Departments.objects.get(pk=department_id)
        department_list.delete()
        # Departamento excluído com sucesso
        return JsonResponse({'success': True})
    except Departments.DoesNotExist:
        # Departamento não encontrado
        return JsonResponse({'success': False, 'error': 'Departamento não encontrado.'})
    
@require_POST
def save_inventory(request):
    inventory_item_id = request.POST.get('inventory_item_id')
    inventory_item = request.POST.get('inventory_item')
    inventory_item_code = request.POST.get('inventory_item_code')
    inventory_quantity = request.POST.get('inventory_quantity')

    if inventory_item_id:
        # Atualizar um item existente
        try:
            inventory_list = Inventory.objects.get(pk=inventory_item_id)
            # Verifica se o nome ou o código são diferentes para evitar conflito de nome ou código únicos
            if (inventory_list.inventory_item != inventory_item and Inventory.objects.filter(inventory_item=inventory_item).exists()) or \
               (inventory_list.inventory_item_code != inventory_item_code and Inventory.objects.filter(inventory_item_code=inventory_item_code).exists()):
                return JsonResponse({'success': False, 'message': 'Por favor, escolha um nome ou código diferente para o item.'})
            inventory_list.inventory_item_code = inventory_item_code
            inventory_list.inventory_item = inventory_item
            inventory_list.inventory_quantity = inventory_quantity
            inventory_list.save()
            return JsonResponse({'success': True, 'message': 'Item atualizado com sucesso.'})
        except Inventory.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Item não encontrado.'})
    else:
        # Criar um novo item
        if Inventory.objects.filter(inventory_item=inventory_item).exists() or Inventory.objects.filter(inventory_item_code=inventory_item_code).exists():
            return JsonResponse({'success': False, 'message': 'Por favor, escolha um nome ou código diferente para o item.'})
        
        new_item = Inventory(
            inventory_item_code=inventory_item_code,
            inventory_item=inventory_item,
            inventory_quantity=inventory_quantity,
            uuid_inventory_item=uuid.uuid4()
        )
        new_item.save()

        return JsonResponse({'success': True, 'message': 'Item adicionado com sucesso.'})

@require_POST
def verify_and_delete_inventory(request, inventory_item_id):
    try:
        # Tenta encontrar e excluir o inventory
        inventory_list = Inventory.objects.get(pk=inventory_item_id)
        inventory_list.delete()
        # Item excluído com sucesso
        return JsonResponse({'success': True})
    except Inventory.DoesNotExist:
        # Item não encontrado
        return JsonResponse({'success': False, 'error': 'Item não encontrado.'})
    
@require_POST
def save_entity(request):
    entity_id = request.POST.get('entity_id')
    entity_type = request.POST.get('entity_type') or None
    full_name = request.POST.get('full_name') or None
    tax_id = request.POST.get('tax_id') or None
    alias_name = request.POST.get('alias_name') or None
    area_code = request.POST.get('area_code') or None
    phone_number = request.POST.get('phone_number') or None
    street = request.POST.get('street') or None
    street_number = request.POST.get('street_number') or None
    state = request.POST.get('state') or None
    city = request.POST.get('city') or None
    postal_code = request.POST.get('postal_code') or None
    email = request.POST.get('email') or None
    bank_name = request.POST.get('bank_name') or None
    bank_branch = request.POST.get('bank_branch') or None
    checking_account = request.POST.get('checking_account') or None
    account_holder_tax_id = request.POST.get('account_holder_tax_id') or None
    account_holder_name = request.POST.get('account_holder_name') or None

    # Determine the appropriate tax ID field
    if tax_id and len(tax_id) <= 14:
        ssn_tax_id = tax_id
        ein_tax_id = None
    else:
        ssn_tax_id = None
        ein_tax_id = tax_id

    # Determine success messages based on entity type
    if entity_type == 'customer':
        update_message = 'Cliente atualizado com sucesso.'

configuracoes/templates/configuracoes.html
{% load static %}

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/configuracoes.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <title>Spifex | Configurações</title>
</head>
<body>
    <header class="header">
        <!-- ############### Barra de Navegação Fixa ############### -->
        <nav class="nav-bar">
            <a class="logo" href="{% url 'cash_flow:cash_flow' %}">Spifex</a>
            <ul class="nav-list">
                <li class="nav-fluxo-de-caixa"><a href="{% url 'cash_flow:cash_flow' %}">Fluxo de Caixa</a></li>
                <li class="nav-realizado"><a href="{% url 'realizado:realizado' %}">Realizado</a></li>
                <li class="nav-relatorios"><a href="#">Relatórios</a></li>
                <li class="nav-line"><div class="line"></div></li>
                <li class="nav-configuracoes"><a href="{% url 'configuracoes:configuracoes' %}">Configurações</a></li>
                <li class="nav-meu-perfil"><a href="meu-perfil.html">Meu Perfil</a></li>
            </ul>
        </nav>
    </header>
    <main class="main">
        <div class="settings-list">
            <section class="accordion-section">
                <a class="accordion-title" href="{% url 'configuracoes:bancos_e_contas' %}">Bancos e Contas</a>
            </section>
            <section class="accordion-section">
                <a class="accordion-title" href="#">Usuários e Permissões</a>
            </section>
            <section class="accordion-section">
                <a class="accordion-title" href="#">Configurações Gerais</a>
            </section>
            <section class="accordion-section">
                <h2 class="accordion-title">Centro de Custos</h2>
                <div class="accordion-content">
                    <ul>
                        <li><a href="{% url 'chart_of_accounts:chart_of_accounts' %}">Plano de Contas</a></li>
                        <li><a href="{% url 'configuracoes:departments' %}">Departamentos</a></li>
                        <li><a href="#">Projetos</a></li>
                        <li><a href="#">Equipamentos e Maquinários</a></li>
                    </ul>
                </div>
            </section>
            <section class="accordion-section accordion-section-stakeholders">
                <h2 class="accordion-title">Stakeholders</h2>
                <div class="accordion-content">
                    <ul>
                        <li><a href="#">Fornecedores</a></li>
                        <li><a href="#">Clientes</a></li>
                        <li><a href="#">Colaboradores</a></li>
                        <li><a href="#">Orgãos Governamentais</a></li>
                    </ul>
                </div>
            </section>
        </div>
        <footer class="footer">
            <p>&copy; Spifex</p>
        </footer>
    </main>
    <script src="{% static 'scripts/scripts-configuracoes.js' %}"></script>
</body>
</html>

configuracoes/templates/settings.html
{% load static %}

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/settings.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <title>Spifex | Configurações</title>
</head>
<body>
    <nav class="navigation-bar">
        <div class="navigation-bar__logo">
            <a href="{% url 'cash_flow:cash_flow' %}" class="navigation-bar__logo--spifex-logo">Spifex</a>
        </div>
        <div class="navigation-bar__tabs">
            <div class="navigation-bar__tabs--tabs">
                <div class="tabs__buttons-list">
                    <a href="{% url 'cash_flow:cash_flow' %}"><button class="tab-button tabs__buttons-list--cash-flow-page">Fluxo de Caixa</button></a>
                    <a href="{% url 'settled_entry:settled_entry' %}"><button class="tab-button tabs__buttons-list--settled-page">Realizado</button></a>
                    <a href="{% url 'reports:cash_flow_report' %}"><button class="tab-button tabs__buttons-list--reports-page">Relatórios</button></a>
                    <div class="tabs__buttons-list--profile-container">
                        <button class="profile-container__account-button">
                            <span class="profile-container__account-button--typography">
                                <div class="profile-container__account-button--details">
                                    <span class="details__text">Perfil</span>
                                        <div class="profile-container__content--svg">
                                            <svg fill="none" viewBox="0 0 24 24" role="none" style="flex: 1 1 0%;"><path fill="currentColor" fill-rule="evenodd" d="m12 17.338 9.665-8.59-1.33-1.495L12 14.662l-8.335-7.41-1.33 1.495L12 17.338Z" clip-rule="evenodd"></path>
                                            </svg>
                                        </div>
                                </div>
                            </span>
                        </button>
                        <div class="profile-dropdown-menu" style="display: none;">
                            <span class="profile-dropdown-menu__item">
                                <a class="profile-dropdown-menu__item--link" href="{% url 'settings:settings' %}">
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" color="#202020" height="20" width="20" xmlns="http://www.w3.org/2000/svg" style="color: #202020;"><path fill="none" d="M0 0h24v24H0z"></path><path d="M12 7V3H2v18h20V7H12zM6 19H4v-2h2v2zm0-4H4v-2h2v2zm0-4H4V9h2v2zm0-4H4V5h2v2zm4 12H8v-2h2v2zm0-4H8v-2h2v2zm0-4H8V9h2v2zm0-4H8V5h2v2zm10 12h-8v-2h2v-2h-2v-2h2v-2h-2V9h8v10zm-2-8h-2v2h2v-2zm0 4h-2v2h2v-2z"></path>
                                    </svg><span class="link__description">Configurações da Empresa</span>
                                </a>
                            </span>
                            <a href="#">
                                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" color="#202020" height="20" width="20" xmlns="http://www.w3.org/2000/svg" style="color: #202020;"><path fill="none" d="M0 0h24v24H0z"></path><path d="M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z"></path></svg>
                                <span>Configurações Pessoais</span>
                            </a>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" color="#202020" width="20" height="20" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16" style="color: #202020;">
                                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2m.995-14.901a1 1 0 1 0-1.99 0A5 5 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901"/>
                              </svg>
                              <span>Preferências de Notificação</span>
                            </a>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" color="#b90000" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16" style="color: #b90000;">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                                </svg>
                              <span style="color: #b90000;">Sair</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <main class="main">
        <div class="settings-list">
            <section class="accordion-section">
                <a class="accordion-title" href="{% url 'settings:banks' %}">Bancos e Contas</a>
            </section>
            <section class="accordion-section">
                <a class="accordion-title" href="#">Usuários e Permissões</a>
            </section>
            <section class="accordion-section">
                <a class="accordion-title" href="#">Configurações Gerais</a>
            </section>
            <section class="accordion-section">
                <h2 class="accordion-title">Centro de Custos</h2>
                <div class="accordion-content">
                    <ul>
                        <li><a href="{% url 'chart_of_accounts:chart_of_accounts' %}">Plano de Contas</a></li>
                        <li><a href="{% url 'settings:departments' %}">Departamentos</a></li>
                        <li><a href="#">Projetos</a></li>
                        <li><a href="#">Equipamentos e Maquinários</a></li>
                    </ul>
                </div>
            </section>
            <section class="accordion-section accordion-section-stakeholders">
                <h2 class="accordion-title">Stakeholders</h2>
                <div class="accordion-content">
                    <ul>
                        <li><a href="#">Fornecedores</a></li>
                        <li><a href="#">Clientes</a></li>
                        <li><a href="#">Colaboradores</a></li>
                        <li><a href="#">Orgãos Governamentais</a></li>
                    </ul>
                </div>
            </section>
        </div>
        <footer class="footer">
            <p>&copy; Spifex</p>
        </footer>
    </main>
    <script src="{% static 'scripts/scripts-configuracoes.js' %}"></script>
</body>
</html>