cash_flow/urls.py
from django.urls import path
from . import views

app_name = 'cash_flow'

urlpatterns = [
    path('', views.cash_flow, name='cash_flow'),
    path('meses_filtro/', views.filter_months_cash_flow, name='filter_months_cash_flow'),
    path('deletar_entradas/', views.delete_entries, name='delete_entries'),
    path('exibir_bancos/', views.display_banks, name='display_banks'),
    path('processar_transferencia/', views.process_transfer, name='process_transfer'),
    path('processar_liquidacao/', views.process_settlement, name='process_settlement'),
    path('pegar_parcelas_relacionadas/<uuid:correlation_id>/', views.get_related_installments, name='get_related_installments'),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('salvar_projeto/', views.save_project, name='save_project'),
]

realizado/urls.py
from django.urls import path
from . import views

app_name = 'realizado'

urlpatterns = [
    path('', views.settled_entry, name='settled_entry'),
    path('meses_filtro_realizado/', views.filter_months_settled, name='filter_months_settled'),
    path('processar_retorno/', views.process_return, name='process_return'),
    path('atualizar-lancamento/<int:id>/', views.update_entry, name='update_entry'),
    path('atualizar-lancamentos-uuid/<str:uuid_transference>/', views.update_entries_by_uuid, name='update_entries_by_uuid'),
]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('', views.reports, name='reports'),
    path('cash_flow_report/', views.cash_flow_report, name='cash_flow_report'),
]

settings/urls.py
from django.urls import path, include
from . import views

app_name = 'settings'

urlpatterns = [
    path('', views.settings, name='settings'),
    path('bancos_e_contas/', views.banks, name='banks'),
    path('departamentos/', views.departments, name='departments'),
    path('estoque/', views.inventory, name='inventory'),
    path('cadastro/', views.entities, name='entities'),
    path('salvar_banco/', views.save_bank, name='save_bank'),
    path('salvar_departamento/', views.save_department, name='save_department'),
    path('salvar_estoque/', views.save_inventory, name='save_inventory'),
    path('salvar_entidade/', views.save_entity, name='save_entity'),
    path('verificar_e_excluir_banco/<int:bank_id>/', views.verify_and_delete_bank, name='verify_and_delete_bank'),
    path('verificar_e_excluir_departamento/<int:department_id>/', views.verify_and_delete_department, name='verify_and_delete_department'),
    path('verificar_e_excluir_estoque/<int:inventory_item_id>/', views.verify_and_delete_inventory, name='verify_and_delete_inventory'),
    path('verificar_e_excluir_entidade/<int:entity_id>/', views.verify_and_delete_entity, name='verify_and_delete_entity'),
]

spifex/urls.py
from django.contrib import admin
from django.urls import path, include
from registration import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fluxo_de_caixa/', include(('cash_flow.urls', 'cash_flow'), namespace='cash_flow')),
    path('realizado/', include(('settled_entry.urls', 'settled_entry'), namespace='settled_entry')),
    path('configuracoes/', include(('settings.urls', 'settings'), namespace='settings')),
    path('accounts/', include('registration.urls')),
    path('home/', views.HomePage, name='home'),
    path('logout/', views.LogoutPage, name='logout'),
    path('configuracoes/plano_de_contas/', include(('chart_of_accounts.urls', 'chart_of_accounts'), namespace='chart_of_accounts')),
    path('relatorios/', include(('reports.urls', 'reports'), namespace='reports')),
    path('configuracoes/projetos/', include(('projects.urls', 'projects'), namespace='projects')),
]

projects/models.py
from django.db import models

class Projects(models.Model):
    project_name = models.CharField(max_length = 100)
    project_code = models.CharField(max_length = 100)
    project_type = models.CharField(max_length = 100)
    project_description = models.CharField(max_length = 256)
    uuid_project = models.UUIDField(null=True, blank=True)

projects/views.py
import uuid
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Projects

def projects(request):
    if request.method =="GET":
        projects_list = Projects.objects.all().order_by('id')

        context = {
            'Projects_list': projects_list,
        }
        return render(request, 'projects.html', context)

def save_project(request):
    if request.method == 'POST':
        project_name = request.POST.get('project_name')
        project_code = request.POST.get('project_id')
        project_type = request.POST.get('project_type')
        project_description = request.POST.get('project_description')
        uuid_project = uuid.uuid4()

        project = Projects(
            project_name=project_name,
            project_code=project_code,
            project_type=project_type,
            project_description=project_description,
            uuid_project=uuid_project
        )
        project.save()

        return JsonResponse({'success': True})
    return JsonResponse({'success': False})

projects/templates/projects.html
{% load static %}
{% load currency_filters %}
{% load number_filters %}
{% load add_decimal %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/projects.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <title>Spifex | Relatório de Fluxo de Caixa</title>
</head>
<body>
    <nav class="navigation-bar">
        <div class="navigation-bar__logo">
            <a href="{% url 'cash_flow:cash_flow' %}" class="navigation-bar__logo--spifex-logo">Spifex</a>
        </div>
        <div class="navigation-bar__tabs">
            <div class="navigation-bar__tabs--tabs">
                <div class="tabs__buttons-list">
                    <a href="{% url 'cash_flow:cash_flow' %}"><button class="tab-button tabs__buttons-list--cash-flow-page">Fluxo de Caixa</button></a>
                    <a href="{% url 'settled_entry:settled_entry' %}"><button class="tab-button tabs__buttons-list--settled-page">Realizado</button></a>
                    <a href="{% url 'reports:reports' %}"><button class="tab-button tabs__buttons-list--reports-page">Relatórios</button></a>
                    <div class="tabs__buttons-list--profile-container">
                        <button class="profile-container__account-button">
                            <span class="profile-container__account-button--typography">
                                <div class="profile-container__account-button--details">
                                    <span class="details__text">Perfil</span>
                                        <div class="profile-container__content--svg">
                                            <svg fill="none" viewBox="0 0 24 24" role="none" style="flex: 1 1 0%;"><path fill="currentColor" fill-rule="evenodd" d="m12 17.338 9.665-8.59-1.33-1.495L12 14.662l-8.335-7.41-1.33 1.495L12 17.338Z" clip-rule="evenodd"></path>
                                            </svg>
                                        </div>
                                </div>
                            </span>
                        </button>
                        <div class="profile-dropdown-menu" style="display: none;">
                            <span class="profile-dropdown-menu__item">
                                <a class="profile-dropdown-menu__item--link" href="{% url 'settings:settings' %}">
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" color="#202020" height="20" width="20" xmlns="http://www.w3.org/2000/svg" style="color: #202020;"><path fill="none" d="M0 0h24v24H0z"></path><path d="M12 7V3H2v18h20V7H12zM6 19H4v-2h2v2zm0-4H4v-2h2v2zm0-4H4V9h2v2zm0-4H4V5h2v2zm4 12H8v-2h2v2zm0-4H8v-2h2v2zm0-4H8V9h2v2zm0-4H8V5h2v2zm10 12h-8v-2h2v-2h-2v-2h2v-2h-2V9h8v10zm-2-8h-2v2h2v-2zm0 4h-2v2h2v-2z"></path>
                                    </svg><span class="link__description">Configurações da Empresa</span>
                                </a>
                            </span>
                            <a href="#">
                                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" color="#202020" height="20" width="20" xmlns="http://www.w3.org/2000/svg" style="color: #202020;"><path fill="none" d="M0 0h24v24H0z"></path><path d="M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z"></path></svg>
                                <span>Configurações Pessoais</span>
                            </a>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" color="#202020" width="20" height="20" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16" style="color: #202020;">
                                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2m.995-14.901a1 1 0 1 0-1.99 0A5 5 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901"/>
                              </svg>
                              <span>Preferências de Notificação</span>
                            </a>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" color="#b90000" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16" style="color: #b90000;">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                                </svg>
                              <span style="color: #b90000;">Sair</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <main class="main">
        <section class="container-buttons">
            <a href="{% url 'settings:settings' %}"><input type="button" class="button-back" name="button-back" value="Voltar"></a>
            <button class="button-add add-project">
                <svg class="svgIcon" width="800px" height="800px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M11 17C11 17.5523 11.4477 18 12 18C12.5523 18 13 17.5523 13 17V13H17C17.5523 13 18 12.5523 18 12C18 11.4477 17.5523 11 17 11H13V7C13 6.44771 12.5523 6 12 6C11.4477 6 11 6.44771 11 7V11H7C6.44772 11 6 11.4477 6 12C6 12.5523 6.44772 13 7 13H11V17Z" fill="#000000"/>
                    </svg>
            </button>
        </section>
        <div class="box-grid-projects">
            <div class="projects-table-wrapper">
                <table class="projects-table">
                    <thead class="projects-table__head">
                        <tr class="projects-table__head--row">
                            <th class="projects-col" scope="col">Projetos</th>
                        </tr>
                    </thead>
                    <tbody class="projects-table__body">
                        {% for projects_item in Projects_list %}
                        <tr class="projects-table__body--row" scope="row" data-id-project="{{ projects_item.id }}" data-uuid-project="{{ projects_item.uuid_project }}">
                            <td class="project-row">{{ projects_item.project_name }} - {{ projects_item.project_code }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- Modal -->
        <dialog class="modal project-modal" id="project-modal">
            <h1 class="modal-title">Projeto</h1>
                <form class="modal-form modal-form-project" action="{% url 'projects:save_project' %}" method="POST">{% csrf_token %}
                    <div class="modal-fields">
                        <input type="hidden" name="id_project" value="{{ projects_item.id }}">
                        <input type="hidden" name="uuid_project" value="{{ projects_item.uuid_project }}">
                        <section class="modal-section project-modal-form__section--project-name section__project-name">
                            <label for="project-name">Nome do projeto*</label>
                            <input class="modal-project-name" id="project-name" type="text" name="project_name" required><br>
                        </section>
                        <section class="modal-section project-modal-form__section--project-id section__project-id">
                            <label for="project-id">Código do projeto*</label>
                            <input class="modal-project-id" id="project-id" type="text" name="project_id" required><br>
                        </section>
                        <section class="modal-section project-modal-form__section--project-type section__project-type">
                            <label for="project-type">Tipo de projeto*</label>
                            <select class="modal-project-type" id="project-type" name="project_type" required>
                            <option value="internal">Interno</option>
                            <option value="external">Externo</option>
                            </select>
                        </section>
                        <section class="modal-section project-modal-form__section--project-description section__project-description mesclar-2">
                            <label for="project-description">Descrição do projeto*</label>
                            <input id="project-description" class="project-description" name="project_description" type="text">
                        </section>
                        <div class="modal-buttons">
                            <input class="modal-save-button-project" type="submit" value="Salvar">
                            <button type="button" class="modal-delete-project" style="display:none;">Apagar</button>
                            <button type="button" class="modal-close-project">Cancelar</button>
                        </div>
                    </div>
                </form>
        </dialog>
    </main> 
    <script src="{% static 'scripts/scripts_projects.js' %}"></script>
</body>
</html>