cash_flow/urls.py
from django.urls import path
from . import views

app_name = 'cash_flow'

urlpatterns = [
    path('', views.cash_flow, name='cash_flow'),
    path('meses_filtro/', views.filter_months_cash_flow, name='filter_months_cash_flow'),
    path('deletar_entradas/', views.delete_entries, name='delete_entries'),
    path('exibir_bancos/', views.display_banks, name='display_banks'),
    path('processar_transferencia/', views.process_transfer, name='process_transfer'),
    path('processar_liquidacao/', views.process_settlement, name='process_settlement'),
    path('pegar_parcelas_relacionadas/<uuid:correlation_id>/', views.get_related_installments, name='get_related_installments'),
]

chart_of_accounts/urls.py
from django.urls import path
from . import views

app_name = 'chart_of_accounts'

urlpatterns = [
    path('', views.chart_of_accounts, name='chart_of_accounts'),
    path('adicionar-conta/', views.add_account, name='adicionar_conta'),
    path('get-groups/', views.get_groups, name='get_groups'),
    path('get-subgroups/', views.get_subgroups, name='get_subgroups'),
    path('editar-conta/<int:account_id>/', views.edit_account, name='edit_account'),
    path('delete-account/<int:account_id>/', views.delete_account, name='delete_account'),
]

realizado/urls.py
from django.urls import path
from . import views

app_name = 'realizado'

urlpatterns = [
    path('', views.settled_entry, name='settled_entry'),
    path('meses_filtro_realizado/', views.filter_months_settled, name='filter_months_settled'),
    path('processar_retorno/', views.process_return, name='process_return'),
    path('atualizar-lancamento/<int:id>/', views.update_entry, name='update_entry'),
    path('atualizar-lancamentos-uuid/<str:uuid_transference>/', views.update_entries_by_uuid, name='update_entries_by_uuid'),
]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('', views.reports, name='reports'),
    path('cash_flow_report/', views.cash_flow_report, name='cash_flow_report'),
]

settings/urls.py
from django.urls import path, include
from . import views

app_name = 'settings'

urlpatterns = [
    path('', views.settings, name='settings'),
    path('bancos_e_contas/', views.banks, name='banks'),
    path('departamentos/', views.departments, name='departments'),
    path('estoque/', views.inventory, name='inventory'),
    path('cadastro/', views.entities, name='entities'),
    path('salvar_banco/', views.save_bank, name='save_bank'),
    path('salvar_departamento/', views.save_department, name='save_department'),
    path('salvar_estoque/', views.save_inventory, name='save_inventory'),
    path('salvar_entidade/', views.save_entity, name='save_entity'),
    path('verificar_e_excluir_banco/<int:bank_id>/', views.verify_and_delete_bank, name='verify_and_delete_bank'),
    path('verificar_e_excluir_departamento/<int:department_id>/', views.verify_and_delete_department, name='verify_and_delete_department'),
    path('verificar_e_excluir_estoque/<int:inventory_item_id>/', views.verify_and_delete_inventory, name='verify_and_delete_inventory'),
    path('verificar_e_excluir_entidade/<int:entity_id>/', views.verify_and_delete_entity, name='verify_and_delete_entity'),
]

spifex/urls.py
from django.contrib import admin
from django.urls import path, include
from registration import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fluxo_de_caixa/', include(('cash_flow.urls', 'cash_flow'), namespace='cash_flow')),
    path('realizado/', include(('settled_entry.urls', 'settled_entry'), namespace='settled_entry')),
    path('configuracoes/', include(('settings.urls', 'settings'), namespace='settings')),
    path('accounts/', include('registration.urls')),
    path('home/', views.HomePage, name='home'),
    path('logout/', views.LogoutPage, name='logout'),
    path('configuracoes/plano_de_contas/', include(('chart_of_accounts.urls', 'chart_of_accounts'), namespace='chart_of_accounts')),
    path('relatorios/', include(('reports.urls', 'reports'), namespace='reports')),
    path('configuracoes/projetos/', include(('projects.urls', 'projects'), namespace='projects')),
]

chart_of_accounts/models.py
from django.db import models
import uuid

class Chart_of_accounts(models.Model):
    CREDITO_DEBITO_CHOICES = [
        ('Crédito', 'Crédito'),
        ('Débito', 'Débito'),
    ]
    GROUP_CHOICES = [
        ('Receitas Operacionais', 'Receitas Operacionais'),
        ('Receitas Não Operacionais', 'Receitas Não Operacionais'),
        ('Despesas Operacionais', 'Despesas Operacionais'),
        ('Despesas Não Operacionais', 'Despesas Não Operacionais'),
    ]

    nature = models.CharField(max_length=255, choices=CREDITO_DEBITO_CHOICES, editable=False)
    group = models.CharField(max_length=255, choices=GROUP_CHOICES)
    subgroup = models.CharField(max_length=255)
    account = models.CharField(max_length=255)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    def save(self, *args, **kwargs):
        if self.group in ['Receitas Operacionais', 'Receitas Não Operacionais']:
            self.nature = 'Crédito'
        else:
            self.nature = 'Débito'
        super(Chart_of_accounts, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.account} ({self.nature})"
    
class Groups_list(models.Model):
    groups_list = models.CharField(max_length=255)
    
class Subgroups_list(models.Model):
    subgroups_list = models.CharField(max_length=255)
    
class Accounts_list(models.Model):
    accounts_list = models.CharField(max_length=255)
    uuid_accounts_list = models.CharField(max_length=255)

chart_of_accounts/forms.py
from django import forms
from .models import Chart_of_accounts

class UploadFileForm(forms.Form):
    file = forms.FileField()

class AccountForm(forms.ModelForm):
    class Meta:
        model = Chart_of_accounts
        fields = ['group', 'subgroup', 'account']

chart_of_accounts/views.py
import openpyxl
from .forms import AccountForm
from django.db import transaction
from .forms import UploadFileForm
from django.contrib import messages
from django.http import JsonResponse
from .models import Chart_of_accounts, Groups_list, Subgroups_list, Accounts_list
from settled_entry.models import SettledEntry
from cash_flow.models import CashFlowEntry
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

def chart_of_accounts(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            excel_file = request.FILES['file']
            wb = openpyxl.load_workbook(excel_file, data_only=True)
            worksheet = wb.active

            # Verification (replace with your actual verification logic)
            if (worksheet['XFD1'].value != "sppiff" or
                    worksheet['XFD2'].value != "1ccd101b-aed4-4b56-b852-02c8ce8a6f70" or
                    worksheet['XFD3'].value != "a5296f55-e314-48d2-8415-f0204d3162f8"):
                messages.error(request, 'A planilha não passou na verificação de segurança.')
                return redirect('/configuracoes/plano_de_contas/')  # Replace with your upload URL

            # Check for used accounts
            used_accounts = set(
                CashFlowEntry.objects.filter(general_ledger_account__in=Chart_of_accounts.objects.values_list('account', flat=True))
                .values_list('general_ledger_account', flat=True)
            ).union(
                SettledEntry.objects.filter(general_ledger_account__in=Chart_of_accounts.objects.values_list('account', flat=True))
                .values_list('general_ledger_account', flat=True)
            )

            if used_accounts:
                messages.error(request, f'As seguintes contas estão sendo utilizadas: {", ".join(used_accounts)}')
                return redirect('/configuracoes/plano_de_contas/')  # Replace with your upload URL

            # Import logic
            with transaction.atomic():
                Chart_of_accounts.objects.all().delete()  # Delete existing accounts

                objects_to_create = []
                for row in worksheet.iter_rows(min_row=2, values_only=True):
                    if row[1] is None:
                        continue
                    objects_to_create.append(
                        Chart_of_accounts(
                            nature=row[0] or '',
                            group=row[1] or '',
                            subgroup=row[2] or '',
                            account=row[3] or ''
                        )
                    )
                Chart_of_accounts.objects.bulk_create(objects_to_create)

    else:
        form = UploadFileForm()

    chart_of_accounts = Chart_of_accounts.objects.all().order_by('-group')
    return render(request, 'chart_of_accounts.html', {'form': form, 'chart_of_accounts': chart_of_accounts})

def add_account(request):
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/configuracoes/plano_de_contas/')
        else:
            print(form.errors)  # Isso ajudará a ver os erros no console do servidor
    else:
        form = AccountForm()
    return render(request, 'add_account_form.html', {'form': form})

def get_groups(request):
    groups = Chart_of_accounts.objects.values('group').distinct()
    groups_with_nature = [
        {'name': group['group'], 'nature': 'Crédito' if group['group'] in ['Receitas Operacionais', 'Receitas Não Operacionais'] else 'Débito'}
        for group in groups
    ]
    return JsonResponse(groups_with_nature, safe=False)

def get_subgroups(request):
    group = request.GET.get('group')
    nature = request.GET.get('nature')
    subgroups = Chart_of_accounts.objects.filter(group=group, nature=nature).values_list('subgroup', flat=True).distinct()
    return JsonResponse(list(subgroups), safe=False)

def edit_account(request, account_id):
    account = get_object_or_404(Chart_of_accounts, id=account_id)
    
    if request.method == 'POST':
        form = AccountForm(request.POST, instance=account)
        if form.is_valid():
            form.save()
        account_uuid = account.uuid
        SettledEntry.objects.filter(uuid_general_ledger_account=account_uuid).update(general_ledger_account=account.account)
        CashFlowEntry.objects.filter(uuid_general_ledger_account=account_uuid).update(general_ledger_account=account.account)

        return redirect('/configuracoes/plano_de_contas/')
    else:
        form = AccountForm(instance=account)
    
    return render(request, 'edit_account_form.html', {'form': form, 'account_id': account_id})

def delete_account(request, account_id):
    account = get_object_or_404(Chart_of_accounts, id=account_id)

    if CashFlowEntry.objects.filter(uuid_general_ledger_account=account.uuid).exists() or \
       SettledEntry.objects.filter(uuid_general_ledger_account=account.uuid).exists():
        messages.error(request, 'Esta conta está sendo utilizada e não pode ser excluída.')
        return redirect('chart_of_accounts:edit_account', account_id)

    account.delete()
    return redirect('/configuracoes/plano_de_contas/')

@receiver(post_save, sender=Chart_of_accounts)
def update_lists_after_save(sender, instance, **kwargs):
    update_groups_list()
    update_subgroups_list()
    update_accounts_list()

@receiver(post_delete, sender=Chart_of_accounts)
def update_lists_after_delete(sender, instance, **kwargs):
    update_groups_list()
    update_subgroups_list()
    update_accounts_list()

def update_groups_list():
    existing_groups = set(Groups_list.objects.values_list('groups_list', flat=True))
    current_groups = set(Chart_of_accounts.objects.values_list('group', flat=True))
    
    for group in current_groups - existing_groups:
        Groups_list.objects.create(groups_list=group)
    
    for group in existing_groups - current_groups:
        Groups_list.objects.filter(groups_list=group).delete()

def update_subgroups_list():
    existing_subgroups = set(Subgroups_list.objects.values_list('subgroups_list', flat=True))
    current_subgroups = set(Chart_of_accounts.objects.values_list('subgroup', flat=True))
    
    for subgroup in current_subgroups - existing_subgroups:
        Subgroups_list.objects.create(subgroups_list=subgroup)
    
    for subgroup in existing_subgroups - current_subgroups:
        Subgroups_list.objects.filter(subgroups_list=subgroup).delete()

def update_accounts_list():
    current_accounts = Chart_of_accounts.objects.all().values_list('uuid', 'account')
    current_accounts_dict = {str(uuid): account for uuid, account in current_accounts}
    existing_accounts_uuids = set(Accounts_list.objects.values_list('uuid_accounts_list', flat=True))

    for uuid, account in current_accounts_dict.items():
        if uuid not in existing_accounts_uuids:
            Accounts_list.objects.create(accounts_list=account, uuid_accounts_list=uuid)
    
    for uuid in existing_accounts_uuids:
        if uuid not in current_accounts_dict:
            Accounts_list.objects.filter(uuid_accounts_list=uuid).delete()

chart_of_accounts/templates/add_account_form.html
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/chart_of_accounts.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <title>Spifex | Plano de Contas</title>
</head>
<body>
    <nav class="navigation-bar">
        <div class="navigation-bar__logo">
            <a href="{% url 'cash_flow:cash_flow' %}" class="navigation-bar__logo--spifex-logo">Spifex</a>
        </div>
        <div class="navigation-bar__tabs">
            <div class="navigation-bar__tabs--tabs">
                <div class="tabs__buttons-list">
                    <a href="{% url 'cash_flow:cash_flow' %}"><button class="tab-button tabs__buttons-list--cash-flow-page">Fluxo de Caixa</button></a>
                    <a href="{% url 'settled_entry:settled_entry' %}"><button class="tab-button tabs__buttons-list--settled-page">Realizado</button></a>
                    <a href="{% url 'reports:reports' %}"><button class="tab-button tabs__buttons-list--reports-page">Relatórios</button></a>
                    <div class="tabs__buttons-list--profile-container">
                        <button class="profile-container__account-button">
                            <span class="profile-container__account-button--typography">
                                <div class="profile-container__account-button--details">
                                    <span class="details__text">Perfil</span>
                                        <div class="profile-container__content--svg">
                                            <svg fill="none" viewBox="0 0 24 24" role="none" style="flex: 1 1 0%;"><path fill="currentColor" fill-rule="evenodd" d="m12 17.338 9.665-8.59-1.33-1.495L12 14.662l-8.335-7.41-1.33 1.495L12 17.338Z" clip-rule="evenodd"></path>
                                            </svg>
                                        </div>
                                </div>
                            </span>
                        </button>
                        <div class="profile-dropdown-menu" style="display: none;">
                            <span class="profile-dropdown-menu__item">
                                <a class="profile-dropdown-menu__item--link" href="{% url 'settings:settings' %}">
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" color="#202020" height="20" width="20" xmlns="http://www.w3.org/2000/svg" style="color: #202020;"><path fill="none" d="M0 0h24v24H0z"></path><path d="M12 7V3H2v18h20V7H12zM6 19H4v-2h2v2zm0-4H4v-2h2v2zm0-4H4V9h2v2zm0-4H4V5h2v2zm4 12H8v-2h2v2zm0-4H8v-2h2v2zm0-4H8V9h2v2zm0-4H8V5h2v2zm10 12h-8v-2h2v-2h-2v-2h2v-2h-2V9h8v10zm-2-8h-2v2h2v-2zm0 4h-2v2h2v-2z"></path>
                                    </svg><span class="link__description">Configurações da Empresa</span>
                                </a>
                            </span>
                            <a href="#">
                                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" color="#202020" height="20" width="20" xmlns="http://www.w3.org/2000/svg" style="color: #202020;"><path fill="none" d="M0 0h24v24H0z"></path><path d="M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z"></path></svg>
                                <span>Configurações Pessoais</span>
                            </a>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" color="#202020" width="20" height="20" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16" style="color: #202020;">
                                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2m.995-14.901a1 1 0 1 0-1.99 0A5 5 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901"/>
                              </svg>
                              <span>Preferências de Notificação</span>
                            </a>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" color="#b90000" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16" style="color: #b90000;">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                                </svg>
                              <span style="color: #b90000;">Sair</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <main class="main">
        <div class="content-container">
            <section class="container-button-back">
                <a href="{% url 'chart_of_accounts:chart_of_accounts' %}"><input type="button" class="button-back" name="button-back" value="Voltar"></a>
            </section>
            <div class="add-account-container">
                <h2>Adicionar Nova Conta</h2>
                <form class="edit-account-form" method="post" action="{% url 'chart_of_accounts:adicionar_conta' %}">
                    {% csrf_token %}
                    <label for="group">Grupo:</label>
                    <select class="edit-field" name="group" id="group" required>
                        <option value="" disabled selected>Selecione um grupo</option>
                    </select>
                    <label for="subgroup">Subgrupo:</label>
                    <select class="edit-field" name="subgroup" id="subgroup" required disabled>
                        <option value="" disabled selected>Selecione um grupo</option>
                    </select>
                    <label for="accountName">Nome da Conta:</label>
                    <input class="edit-field" type="text" id="accountName" name="account" required>
                    <section class="btn-section">
                        <button type="submit" class="btn btn-success">Salvar</button>
                    </section>
                </form>
            </div>
        </div>
    </main>
    <script type="text/javascript">
        var getSubgroupsUrl="{% url 'chart_of_accounts:get_subgroups' %}";
        var getGroupsUrl="{% url 'chart_of_accounts:get_groups' %}";
    </script>
    <script src="{% static 'scripts/add_account_form.js' %}"></script>
</body>
</html>

chart_of_accounts/templates/edit_account_form.html
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/chart_of_accounts.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <title>Spifex | Plano de Contas</title>
</head>
<body>
    <nav class="navigation-bar">
        <div class="navigation-bar__logo">
            <a href="{% url 'cash_flow:cash_flow' %}" class="navigation-bar__logo--spifex-logo">Spifex</a>
        </div>
        <div class="navigation-bar__tabs">
            <div class="navigation-bar__tabs--tabs">
                <div class="tabs__buttons-list">
                    <a href="{% url 'cash_flow:cash_flow' %}"><button class="tab-button tabs__buttons-list--cash-flow-page">Fluxo de Caixa</button></a>
                    <a href="{% url 'settled_entry:settled_entry' %}"><button class="tab-button tabs__buttons-list--settled-page">Realizado</button></a>
                    <a href="{% url 'reports:reports' %}"><button class="tab-button tabs__buttons-list--reports-page">Relatórios</button></a>
                    <div class="tabs__buttons-list--profile-container">
                        <button class="profile-container__account-button">
                            <span class="profile-container__account-button--typography">
                                <div class="profile-container__account-button--details">
                                    <span class="details__text">Perfil</span>
                                        <div class="profile-container__content--svg">
                                            <svg fill="none" viewBox="0 0 24 24" role="none" style="flex: 1 1 0%;"><path fill="currentColor" fill-rule="evenodd" d="m12 17.338 9.665-8.59-1.33-1.495L12 14.662l-8.335-7.41-1.33 1.495L12 17.338Z" clip-rule="evenodd"></path>
                                            </svg>
                                        </div>
                                </div>
                            </span>
                        </button>
                        <div class="profile-dropdown-menu" style="display: none;">
                            <span class="profile-dropdown-menu__item">
                                <a class="profile-dropdown-menu__item--link" href="{% url 'settings:settings' %}">
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" color="#202020" height="20" width="20" xmlns="http://www.w3.org/2000/svg" style="color: #202020;"><path fill="none" d="M0 0h24v24H0z"></path><path d="M12 7V3H2v18h20V7H12zM6 19H4v-2h2v2zm0-4H4v-2h2v2zm0-4H4V9h2v2zm0-4H4V5h2v2zm4 12H8v-2h2v2zm0-4H8v-2h2v2zm0-4H8V9h2v2zm0-4H8V5h2v2zm10 12h-8v-2h2v-2h-2v-2h2v-2h-2V9h8v10zm-2-8h-2v2h2v-2zm0 4h-2v2h2v-2z"></path>
                                    </svg><span class="link__description">Configurações da Empresa</span>
                                </a>
                            </span>
                            <a href="#">
                                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" color="#202020" height="20" width="20" xmlns="http://www.w3.org/2000/svg" style="color: #202020;"><path fill="none" d="M0 0h24v24H0z"></path><path d="M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z"></path></svg>
                                <span>Configurações Pessoais</span>
                            </a>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" color="#202020" width="20" height="20" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16" style="color: #202020;">
                                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2m.995-14.901a1 1 0 1 0-1.99 0A5 5 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901"/>
                              </svg>
                              <span>Preferências de Notificação</span>
                            </a>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" color="#b90000" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16" style="color: #b90000;">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                                </svg>
                              <span style="color: #b90000;">Sair</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <main class="main">
        <div class="content-container">
            <section class="container-button-back">
                <a href="{% url 'chart_of_accounts:chart_of_accounts' %}"><input type="button" class="button-back" name="button-back" value="Voltar"></a>
            </section>
            {% block content %}
            <div class="edit-account-container">
                <h2>Editar Conta</h2>
                <form class="edit-account-form" method="post" action="{% url 'chart_of_accounts:edit_account' account_id %}">
                    {% csrf_token %}
                    <label for="group">Grupo:</label>
                    <select class="edit-field" name="group" id="group" required>
                        <option value="" disabled selected>Selecione um grupo</option>
                    </select>
        
                    <label for="subgroup">Subgrupo:</label>
                    <select class="edit-field" name="subgroup" id="subgroup" required disabled>
                        <option value="" disabled selected>Selecione um subgrupo</option>
                    </select>
        
                    <label for="account">Conta:</label>
                    <input class="edit-field" type="text" id="account" name="account" required>
        
                    <section class="btn-section">
                        <button type="submit" class="btn btn-success">Salvar Alterações</button>
                        <a href="{% url 'chart_of_accounts:delete_account' account_id %}" class="btn btn-delete" onclick="return confirm('Tem certeza de que deseja excluir esta conta?')">Excluir Conta</a>
                    </section>
                </form>
            </div>
            {% endblock %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </main>
    <script type="text/javascript">
        var getSubgroupsUrl="{% url 'chart_of_accounts:get_subgroups' %}";
        var getGroupsUrl="{% url 'chart_of_accounts:get_groups' %}";
    </script>
    <script src="{% static 'scripts/edit_account_form.js' %}"></script>
</body>
</html>